[project]
name = "mcp-server-demo"
version = "0.1.0"
description = " this is Simple MCP server for adding two number"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.12.3",
]
